src/Entity/Tag.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TagRepository")
 */
class Tag
{

    public function __toString()
    {
        return $this->getNameTag();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $name_tag;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Product", inversedBy="tags")
     */
    private $product;

    public function __construct()
    {
        $this->product = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameTag(): ?string
    {
        return $this->name_tag;
    }

    public function setNameTag(string $name_tag): self
    {
        $this->name_tag = $name_tag;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProduct(): Collection
    {
        return $this->product;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->product->contains($product)) {
            $this->product[] = $product;
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->product->contains($product)) {
            $this->product->removeElement($product);
        }

        return $this;
    }
}

src/Form/TagType.php
<?php

namespace App\Form;

use App\Entity\Tag;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TagType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name_tag')
            ->add('product',null,  array('expanded' => true, 'multiple' => true, 'required' => false, 'label' => false, 'by_reference' => false))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tag::class,
        ]);
    }
}

src/Controller/TagController.php
<?php

namespace App\Controller;

use App\Entity\Tag;
use App\Form\TagType;
use App\Repository\TagRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("admin/tag")
 */
class TagController extends AbstractController
{
    /**
     * @Route("/", name="tag_index", methods={"GET"})
     */
    public function index(TagRepository $tagRepository): Response
    {
        return $this->render('tag/index.html.twig', [
            'tags' => $tagRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="tag_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $tag = new Tag();
        $form = $this->createForm(TagType::class, $tag);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tag);
            $entityManager->flush();

            return $this->redirectToRoute('tag_index');
        }

        return $this->render('tag/new.html.twig', [
            'tag' => $tag,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tag_show", methods={"GET"})
     */
    public function show(Tag $tag): Response
    {
        return $this->render('tag/show.html.twig', [
            'tag' => $tag,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="tag_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Tag $tag): Response
    {
        $form = $this->createForm(TagType::class, $tag);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('tag_index');
        }

        return $this->render('tag/edit.html.twig', [
            'tag' => $tag,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tag_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tag $tag): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tag->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($tag);
            $entityManager->flush();
        }

        return $this->redirectToRoute('tag_index');
    }
}

templates/tag/_delete_form.html.twig
<form method="post" action="{{ path('tag_delete', {'id': tag.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tag.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tag/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tag/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tag{% endblock %}

{% block body %}
    <h1>Edit Tag</h1>

    {{ include('tag/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('tag_index') }}">back to list</a>

    {{ include('tag/_delete_form.html.twig') }}
{% endblock %}

templates/tag/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tag index{% endblock %}

{% block body %}
    <h1>Tag index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name_tag</th>
                <th>Nombre de produits</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for tag in tags %}
            <tr>
                <td>{{ tag.id }}</td>
                <td>{{ tag.nameTag }}</td>
                <td>{{ tag.product.count }}</td>
                <td>
                    <a href="{{ path('tag_show', {'id': tag.id}) }}">show</a>
                    <a href="{{ path('tag_edit', {'id': tag.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('tag_new') }}">Create new</a>
{% endblock %}

templates/tag/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tag{% endblock %}

{% block body %}
    <h1>Create new Tag</h1>

    {{ include('tag/_form.html.twig') }}

    <a href="{{ path('tag_index') }}">back to list</a>
{% endblock %}

templates/tag/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tag{% endblock %}

{% block body %}
    <h1>Tag</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tag.id }}</td>
            </tr>
            <tr>
                <th>Name_tag</th>
                <td>{{ tag.nameTag }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('tag_index') }}">back to list</a>

    <a href="{{ path('tag_edit', {'id': tag.id}) }}">edit</a>

    {{ include('tag/_delete_form.html.twig') }}
{% endblock %}